[package]
authors = ["Jacek Chmielewski <jchmielewski@teonite.com>"]
edition = "2018"
name = "hirez"
version = "0.1.0"
[dependencies]
clap = "*"
colored = "*"
scraper = "*"

[dependencies.reqwest]
features = ["blocking"]
version = "*"
